version: "3"

services:

  pgadmin4:
    image: thajeztah/pgadmin4
    container_name: pgadmin4
    ports:
      - 5050:5050

    volumes:
      - pgadmin_data:/pgadmin
      
volumes:
  pgadmin_data: