version: 3.7

services:
  redis:
    image: redis:5
    container_name: redis
    restart: unless-stopped
    ports: "6379:6379"
    volumes:
      - redis:/data
    networks:
      dev_space:
        ipv4_address: "172.20.0.20"

networks:
  dev_space:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0"

volumes:
  redis:
