version: 3.7

services:

  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: unless-stopped
    ports:
      - 50000:50000
      - 58080:8080
    networks:
      - dev_space:
        ipv4_address: "172.20.0.10"
    volumes:
      - jenkins: /var/jenkins_home

networks:
  dev_space:
    ipam:
      driver: default
      config:
        -subnet: "172.20.0.0"

volumes:
  jenkins:
